GET http://localhost:5000/users

### 
POST http://localhost:5000/users 
Content-Type: application/json

{
"nama_penyewa": "arfan",
"alamat": "Karawaci", 
"tgl_sewa": "12-12-2023", 
"durasi": 2,
"lokasi_ambil": "Diantar",
"lokasi_kembali": "Di kantor",
"email": "arfan@gmail.com",
"no_telp": "081299219213",
"totalHarga": 150000,
"mobId": 1
}

###
PATCH  http://localhost:5000/users/7
Content-Type: application/json

{
"name": "Arvan", "email": "arvamgamteng@gmail.com", "gender": "Male"
}

###
DELETE http://localhost:5000/users/8

####################


GET http://localhost:5000/mobil


###
GET http://localhost:5000/mobil/2

### 
POST http://localhost:5000/mobil
Content-Type: application/json

{
    "nama": "Innova Zenix",
    "harga": "500000",
    "foto": "https://cdn.motor1.com/images/mgl/QeYwvO/s3/toyota-innova-zenix.jpg"
}

###
PATCH http://localhost:5000/mobil/2
Content-Type: application/json

{
    "nama": "Toyota Alphard",
    "harga": "1000000",
    "foto": "https://imgcdn.oto.com/large/gallery/color/38/1917/toyota-alphard-color-856953.jpg"
}


###
DELETE http://localhost:5000/products/2
