GET http://localhost:5000/users

### 
POST http://localhost:5000/users 
Content-Type: application/json

{
"nama penyewa": "Clavino",
"alamat": "Taman Cibodas", 
"tgl_sewa": "01-10-2023", 
"durasi": "02-10-2023", 
"no_telp": 0812, 
"lokasi_ambil": "clavino@gmail.com", 
"lokasi_kembali": "082195808930", 
"mobId": ,
}

###
PATCH  http://localhost:5000/users/7
Content-Type: application/json

{
"name": "Arvan", "email": "arvamgamteng@gmail.com", "gender": "Male"
}

###
DELETE http://localhost:5000/users/8

####################


GET http://localhost:5000/destinasi


###
GET http://localhost:5000/destinasi/2

### 
POST http://localhost:5000/mobil
Content-Type: application/json

{
    "nama": "Toyota Camry",
    "harga": "Rp.500000",
    "foto": "mobil.jpg",
}

###
PATCH http://localhost:5000/destinasi/2
Content-Type: application/json

{
    "tujuan": "Bandung",
    "harga": "Rp.250.000,00"
}


###
DELETE http://localhost:5000/products/2
